//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuanLyHocNgheCuaHung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChungChi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChungChi()
        {
            this.ChungChiSinhViens = new HashSet<ChungChiSinhVien>();
        }
    
        public int MaChungChi { get; set; }
        public string TenChungChi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChungChiSinhVien> ChungChiSinhViens { get; set; }
    }
}
