//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuanLyHocNgheCuaHung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HuanLuyenVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HuanLuyenVien()
        {
            this.HopDongs = new HashSet<HopDong>();
        }
    
        public string IDHuanLuyenVien { get; set; }
        public string HoTen { get; set; }
        public string DienThoai { get; set; }
        public string BoPhan { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HopDong> HopDongs { get; set; }
    }
}
